# -*- coding: utf-8 -*-
"""Excellors-HouseWorth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UyWaXBJAKrlL5V0L9msfY5ZHsd69kQS-

## TASK : Exploratory Data Analysis
By- Aditya Gollapalli and Vaishnavi Vijayashankar

**Exploratory data analysis (EDA) is used by data scientists to analyze and investigate data sets and summarize their main characteristics, often employing data visualization methods.**

The dataset that we are using is ***train.csv*** and our project aim is to predict whether a house is worthy or not. In this sprint, we are performing EDA for the given dataset to analyse interesting insights
"""

#importing all the suitable libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use("seaborn-whitegrid")

#Creating the dataframe
train=pd.read_csv('/content/train.csv')

#printing the contents
train.head()

#displaying No. of Rows and Columns
train.shape

#displaying Statistics Summary
train.describe()

"""***As we see the above 2 outputs, we have both Numberical and categorical attributes, so we perform data visualization for both.***

For Neighborhood
"""

#Displaying Total Number of Neighborhoods
train["Neighborhood"].count()

#Displaying Total count of Each Neighborhoods
train["Neighborhood"].value_counts()

#Categorising Neighborhood based on the sales price average
train[["Neighborhood","SalePrice"]].groupby(by="Neighborhood",as_index=False).mean().sort_values(by="SalePrice",ascending=False)

"""






       BrDale	Briardale
       BrkSide	Brookside
       ClearCr	Clear Creek
       CollgCr	College Creek
       Crawfor	Crawford
       Edwards	Edwards
       Gilbert	Gilbert
       IDOTRR	Iowa DOT and Rail Road
       MeadowV	Meadow Village
       Mitchel	Mitchell
       Names	North Ames
       NoRidge	Northridge
       NPkVill	Northpark Villa
       NridgHt	Northridge Heights
       NWAmes	Northwest Ames
       OldTown	Old Town
       SWISU	South & West of Iowa State University"""

sns.set(rc={'figure.figsize':(15.7,8.27)})
sns.boxplot(x="Neighborhood", y="SalePrice", data=train)
plt.xticks(rotation=90)
plt.show()

"""### *It is seen that Northridge, Northridge Heights and Stony Brook are the most expensive neighborhoods. Northridge Heights has a signficantly large range in the sale price of the houses.*

Let's Analayse the SafeRAtes for each Neighborhood
"""

fig = plt.figure(figsize=(20, 6))
ax = fig.add_axes([0,0,1,1])
ax.bar(train['Neighborhood'],train['SafeRate'])
plt.xticks(rotation=90)
plt.show()

train_sorted= train.sort_values('SafeRate',ascending=False)
plt.figure(figsize=(10,6))
# bar plot with matplotlib
plt.bar(train['Neighborhood'],train['SafeRate'],data=train_sorted)
plt.xlabel("Neighborhood", size=15)
plt.ylabel("SafeRate", size=15)
plt.xticks(rotation=90)
plt.title("SafeRates in each place", size=18)

"""On comparing this graph with the previous graph, there is some relationship between 3 attributes

1.   Average(SalesPrice)
2.   Neighborhood Counts
3.   Safe Rates for each neighborhood

1-10 where 1 is more safe and 10 is risky
For example, "Veenker" is a place and its crime rate is 8 which is a risky place and in total only 11 houses have been sold and the average salesprice is $ 238772.72 which is high.

Let's Consider the Second example "NAmes". The Safe rate is kinda less (i.e,0.2) and 225 houses have been sold at a nominal rate. People would like to buy houses in a place where the neighborhood is safe.

For Overall Quality
"""

train[["OverallQual","SalePrice"]].groupby(by="OverallQual",as_index=False).mean().sort_values(by="SalePrice",ascending=False)

"""The salesprice is increasing as the quality improves"""

train[["OverallCond","SalePrice"]].groupby(by="OverallCond",as_index=False).mean().sort_values(by="SalePrice",ascending=False)

"""The relationship between the condition and salesprice seems to be average

Sale Type
"""

train["SaleType"].value_counts()

ax2 = train.plot.scatter(x='SaleType',y='SalePrice',c='DarkBlue',alpha=0.5)

"""Warranty Deed(WD) is a deed that guarantees a clear title to the buyer of real property. The buyer, or grantee, of a property benefits the most from obtaining a warranty deed. Through the recording of a warranty deed, the seller is providing assurances to the buyer should anything unexpected happen. Hence, those sales are extremely popular at all prices, followed by new homes, which have a higher price as is intuitive.

Checking for Relationship Between Overall Quality and Year Built
"""

ax2 = train.plot.scatter(x='YearBuilt',y='OverallQual',c='Red',alpha=0.5)

"""There seems to be a minor correlationship between the year built and overall quality. The quality rates are slowing improving as the year increases.

Garage Size
"""

fig, ax = plt.subplots()
ax.scatter(x = train['GrLivArea'], y = train['SalePrice'])
plt.ylabel('SalePrice', fontsize=13.5)
plt.xlabel('GrLivArea', fontsize=13.5)
plt.show()

"""Garage size is shown to have an effect on the house price till the size reaches 2000 sq.ft.

Year Built
"""

fig, ax = plt.subplots()
ax.scatter(x = train['YearBuilt'], y = train['SalePrice'])
plt.ylabel('SalePrice', fontsize=13.5)
plt.xlabel('YearBuilt', fontsize=13.5)
plt.show()

"""From the year 1950 and till 2010 there is no suddend surge in the sales price. There is a slight increase

#CONCLUSION
## The location of the property has an influence on its price, with certain areas having substantially larger ranges of houses sold. Surprisingly, the house is more likely to sell in May or June than than December or January. A Warranty Deed would make it easier for a seller to sell a house.The location of the house would also influence the price of the house. The size of a garage may merit an increase in the price of a house up to a point, but after that, the influence lessens.
"""

